#!/bin/bash

# ============================================================
# IQ-TREE 3 - PMSF ANALYSIS
#
# This script performs the PMSF analysis using the guide tree
# generated in the previous IQ-TREE step.
#
# IMPORTANT:
# Run the standard IQ-TREE analysis first and use its
# resulting .treefile as GUIDE_TREE.
# ============================================================


# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------

# Path to IQ-TREE 3 executable
IQ_TREE_PATH=##                 # Change this

# Input concatenated amino-acid alignment
FILE_INPUT=##                   # Change this

# Guide tree from the previous IQ-TREE analysis
#
# This should be the .treefile generated by the standard
# LG+C60 tree inference step.
GUIDE_TREE=##                   # Change this

# Number of CPU threads
THREADS=100                     # Reduce if fewer CPUs are available

# Maximum memory available to IQ-TREE
MEMORY="1500G"                  # Reduce if less RAM is available

# Type of amino-acid substitution models
MSUB="nuclear"

# Number of replicates used for both:
#
#   - ultrafast bootstrap
#   - SH-aLRT
BRANCH_TEST_REPLICATES=1000

# PMSF model
#
# Fixed for this analysis.
AUTOMATIC_MODEL_SELECTION="LG+C60+F+G"

# Output prefix
OUTPUT_PREFIX=##                # Change this


# ------------------------------------------------------------
# PMSF SETTINGS
# ------------------------------------------------------------

# -m LG+C60+F+G
#   Model used for the PMSF analysis.
#
# -ft
#   Supply the guide tree generated in the previous
#   IQ-TREE analysis.
#
# -msub nuclear
#   Use the nuclear amino-acid model subset.
#
# -bb 1000
#   Run 1000 ultrafast bootstrap replicates.
#
# -alrt 1000
#   Run 1000 SH-aLRT replicates.


# ------------------------------------------------------------
# CHECK INPUT
# ------------------------------------------------------------

if [ ! -x "${IQ_TREE_PATH}" ]; then
    echo "ERROR: IQ-TREE executable not found or not executable:"
    echo "${IQ_TREE_PATH}"
    exit 1
fi

if [ ! -f "${FILE_INPUT}" ]; then
    echo "ERROR: Input alignment not found:"
    echo "${FILE_INPUT}"
    exit 1
fi

if [ ! -f "${GUIDE_TREE}" ]; then
    echo "ERROR: Guide tree not found:"
    echo "${GUIDE_TREE}"
    exit 1
fi


# ============================================================
# RUN IQ-TREE PMSF
# ============================================================

echo
echo "============================================================"
echo "Running IQ-TREE 3 - PMSF"
echo "============================================================"
echo
echo "Input alignment:      ${FILE_INPUT}"
echo "Guide tree:           ${GUIDE_TREE}"
echo "Output prefix:        ${OUTPUT_PREFIX}"
echo "Model:                ${AUTOMATIC_MODEL_SELECTION}"
echo "Model subset:         ${MSUB}"
echo "Threads:              ${THREADS}"
echo "Bootstrap replicates: ${BRANCH_TEST_REPLICATES}"
echo "SH-aLRT replicates:   ${BRANCH_TEST_REPLICATES}"
echo "Memory limit:         ${MEMORY}"
echo


"${IQ_TREE_PATH}" \
    -nt "${THREADS}" \
    -m "${AUTOMATIC_MODEL_SELECTION}" \
    -msub "${MSUB}" \
    -s "${FILE_INPUT}" \
    -bb "${BRANCH_TEST_REPLICATES}" \
    -alrt "${BRANCH_TEST_REPLICATES}" \
    -pre "${OUTPUT_PREFIX}" \
    -ft "${GUIDE_TREE}" \
    -mem "${MEMORY}" \
    || {
        echo "ERROR: IQ-TREE PMSF analysis failed."
        exit 1
    }


echo
echo "============================================================"
echo "IQ-TREE PMSF analysis completed successfully"
echo "============================================================"
